theme = "onedark"

[editor]
true-color = true
line-number = "relative"

[keys.insert]
f = { d ="normal_mode"} # map fd to esc

[keys.normal]
C-s = ":w"
X = "extend_line_above"
"^" = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_file_end"
C-r = "redo"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

