[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} 
auto-format = true

[[language]]
name = "rust"
auto-format = true